### ISSUE TITLE
Ximea camera issues. 

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/cockpit#536]
Trying to connect to a Ximea camera through cockpit and it was unable to find the correct trigger type. Itr is looking for 

Xi_TRG_SOFTWARE

Do we need to update microscope on the cockpit machine?

**Comment by iandobbie** [comment]
This is meant to be mapped with 
        if trig==XI_TRG_SOFTWARE:
            return devices.TRIGGER_SOFT
Dont understand why this isnt working.

**Comment by iandobbie** [comment]
I think this is all solved by Nick's code that has been importated into microscope and cleaned up by david. I think we should close this issue.

**Comment by iandobbie** [comment]
I still think there is an issue with trigger types, surely we should be setting TriggerType.SOFTWARE and not a device specific one.

**Comment by carandraug** [comment]
> I still think there is an issue with trigger types, surely we should be setting TriggerType.SOFTWARE and not a device specific one.

The `Camera` interface did not use to have methods to get the trigger type. There was `get_trigger_type` but to actually change it one always had to go through the settings dict. The settings dict is for hardware specific things, for when one wants to bypass the defined interface of the ABC. For example, while cameras do have `set_binning` and `get_binning` methods, these are also exposed in the settings dict with something closer to the hardware (which in some cases means having separate settings for vertical and horizontal binning).

Now that `Camera` does have `set_trigger` method, someone could add a standard UI to the cockpit camera panel to do it. However, it's worth considering whether that's something we want to expose. I know this issue is because the microscope-aotools expect a specific trigger type/mode configuration. Maybe microscope-aotools should set it as required and then return back to what it was before.

Whatever the solution is, it shouldn't be modifying the settings dict of the ximea implementing to use something "standard". The whole point of the settings dict is for when one wants to be closer to the native hardware settings and not use the standard interface.

**Comment by iandobbie** [comment]
This issue is fixed as far as I know and the trigger types and modes have been substantially changed since this bug report so I will close this and if it is still a problem someone can reopen it.
