### ISSUE TITLE
lights panel with colour does not work on Mac

### ISSUE THREAD

**Issue by ARCFaria** [MicronOxford/cockpit#723]
The thin line under the light name that is supposed to show the light wavelength is always grey on a Mac.

![image](https://user-images.githubusercontent.com/44144243/110250946-6f9b7d00-7f7e-11eb-8017-427da5bf7766.png)

**Comment by iandobbie** [comment]
The camera colour indicators also dont work. The title bar in the camera views works but the bar under the camera name in the main window does not take a colour.

**Comment by carandraug** [comment]
This is currently done with:

        line = wx.StaticBox(self, size=(-1,4), style=wx.LI_HORIZONTAL)
        line.SetBackgroundColour(wavelengthToColor(self.light.wavelength))

Which creates an empty control with a dark grey line around (the static box) and colours the background. If one looks closely on the screenshoot above, one can see the dark grey colour from the grey colour as well as a lighter grey which is the outside of the static box. Because the grey line is not the background, it is not affected by the `SetBackgroundColour`. This works in Linux and Windows because there's a margin between the start of control and the actual static box line, which is larger than the size we're giving to the whole control. See in Linux if we increase its height to 20:

![lights-panel](https://user-images.githubusercontent.com/916140/110326877-25afa700-8011-11eb-9c43-637907284c72.png)

There might still be a problem with mac ignoring `SetBackgroundColour` but that's not the whole thing.

At least for starter, replacing the use of `wx.StaticBox` with simply `wx.Control` might help. If that does not work in Mac, then Mac really is ignoring `SetBackgroundColour`. I don't think there's any wx control for this only, so maybe we would need a `wx.ClientDC` that we paint whatever colour we want.

@ARCFaria can you try my "723-control-for-colour" branch and see if that fixes it?

**Comment by iandobbie** [comment]
![image](https://user-images.githubusercontent.com/5451909/110354013-9f568d80-802f-11eb-804b-7fd515f71861.png)
Seems to work on my mac

**Comment by iandobbie** [comment]
Obviously also needs to be applied to the cameras as well, although these might not have colours.

**Comment by carandraug** [comment]
Thank you for testing. I have pushed the fix to master. It should also fix the colour under the cameras (but that needs a drawer or filterwheel device to set a colour for the camera. Such dummy devices are not part of the dummy devices created automatically by cockpit which is why they are appearing grey on your case).

Closing as fixed.

Since I was looking at the code I also changed the height of the line to be function of the font size (instead of hardcoded to 4 pixels).
