### ISSUE TITLE
remote object has no exposed attribute or method 'may_move_on_enable'

### ISSUE THREAD

**Issue by Jakob-We** [MicronOxford/cockpit#827]
[20220927_Tue-0747.log](https://github.com/MicronOxford/cockpit/files/9652091/20220927_Tue-0747.log)
When starting up a fresh install of cockpit with:
`python -m cockpit`
it can not start with the attached log.
Looks like the DummyStage dosent support the may_move_on_enable.
Operation system: Windows 10.
Python version: v3.9.2:1a79785

**Comment by juliomateoslangerak** [comment]
I believe this is because the cockpit installation is not pulling the last changes from python-microscope.

In your environment, if you do `pip list` you will probably see microscope version 0.6.0.
Can you try to uninstall microscope `pip uninstall microscope` and reinstall it from the git source `pip install git+https://github.com/python-microscope/microscope.git`?
