### ISSUE TITLE
Updating stage limits on stages that need to initialise.

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/cockpit#842]
Some stages, such as the Ludl need to move to the limits to actually find their true motion limits on enable. There is now a function in the stage abc to say the stage might move on enable, if this is triggered the stage motion limits should be updated after this motion check.

**Comment by carandraug** [comment]
I still don't understand what the problem is. Here's the series of events related to this that should be happening during cockpit startup:

1. cockpit app initializes devices in depot
1.2 depot constructs `MicroscopeStage`
1.2 depot calls `MicroscopeStage.initialize`
1.3 `MicroscopeStage.initialize` calls `self._proxy.enable` (which triggers the move which define the limits in the remote) and creates a list of `PositionerHandler` (indirectly through the `_MicroscopeStageAxis`)
4. cockpit app initializes `stageMover`
4.1 `StageMover.initialize` computes the hard limits

Since moves and query of limits are (or should) always be done through `StageMover`, and since `StageMover` is only constructed after depot has initialized all stages, we shouldn't be getting cases where the limits are not available.

**Comment by iandobbie** [comment]
No I'm afraid that is not how the information flow is progressing. 
1) Depot constructs a stage, 
2) in the stage Initialize, each axis is created and appended to self._axes, about line 550 of microscopeDevices.py
3) this creates a _MicroscopeStageAxis object which creates a handler of type PositionHandler, which establishes the limits
4) At the final steps of the stage initialize the stage is enabled which defines the real limits, different from the made up limits that the PositionHandler was established with. 

So either the limits need to reset after the enable call in MicroscopeStage.inialise or the enable needs to be done in the MicroscopeStageAxis class, but this would require multiple "stage may move" warnings and is rather counter intuitive.

**Comment by carandraug** [comment]
I see now. WHat if we just move the block that calls enable on the stage to the start of `MicroscopeStage.initialize`, i.e., before the `_MicroscopeStageAxis` are constructed?

**Comment by iandobbie** [comment]
I am just testing this, broken it with stupid minor code errors several times so far.

**Comment by iandobbie** [comment]
This seems to solve all the problems, no need to reset the hardlimits and the macrosatge and mosaic windows are now properly mapped to the stage. I will pull a proper fix.

**Comment by iandobbie** [comment]
Just noticed and issue. If may_move_on_enable() is false the stage will never be enabled!
Do we need another if statement that checks if the stage is enabled and  runs enable if needed?

**Comment by iandobbie** [comment]
Added code to enable if not enabled and it bypasses the current enable. All seem to work fine for me so pulled it as feb1e75b056bb8bd23d5bb48e94e6632e1143701

**Comment by carandraug** [comment]
> Can you do that? Don't we need the axis to be constrcuted before we operate on them. I guess it is easy to try.

The remote side (Python-Microscope) has already constructed the its instances which will sort the limits as expected. What this changes is the timing when Cockpit constructs the `cockpit.devices.microscopeDevice._MicroscopeStageAxis` which only reads the limits once.
